export const ERROR_CODES = {
  ERR_TIMEOUT: 'ERR_TIMEOUT',
  ERR_NOT_FOUND: 'ERR_NOT_FOUND',
  ERR_STALE: 'ERR_STALE',
  ERR_UNSUPPORTED: 'ERR_UNSUPPORTED',
  ERR_ASSERTION_FAILED: 'ERR_ASSERTION_FAILED',
  ERR_DIALOG_BLOCKED: 'ERR_DIALOG_BLOCKED',
  ERR_POPUP_BLOCKED: 'ERR_POPUP_BLOCKED',
  ERR_BAD_ARGS: 'ERR_BAD_ARGS'
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
