export const ERROR_CODES = {
    ERR_TIMEOUT: 'ERR_TIMEOUT',
    ERR_NOT_FOUND: 'ERR_NOT_FOUND',
    ERR_STALE: 'ERR_STALE',
    ERR_UNSUPPORTED: 'ERR_UNSUPPORTED',
    ERR_ASSERTION_FAILED: 'ERR_ASSERTION_FAILED',
    ERR_DIALOG_BLOCKED: 'ERR_DIALOG_BLOCKED',
    ERR_POPUP_BLOCKED: 'ERR_POPUP_BLOCKED',
    ERR_BAD_ARGS: 'ERR_BAD_ARGS',
    ERR_WORKFLOW_BAD_ARGS: 'ERR_WORKFLOW_BAD_ARGS',
    ERR_WORKSPACE_SNAPSHOT_NOT_FOUND: 'ERR_WORKSPACE_SNAPSHOT_NOT_FOUND',
    ERR_WORKSPACE_RESTORE_FAILED: 'ERR_WORKSPACE_RESTORE_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
